Repository nano-devs/Musicfy-Bot, pull requests merged in 2020-11, with the labels that each got.

#37 Fix 20201101
  src/main/java/Main.java
  src/main/java/command/GuildPlaylistCommand/DeletePlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/ShowPlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/ShowPlaylistTrackCommand.java
  src/main/java/command/UserPlaylistCommand/DeletePlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/RenamePlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/ShowPlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/ShowPlaylistTrackCommand.java
  src/main/java/command/history/GuildHistoryCommand.java
  src/main/java/command/history/UserHistoryCommand.java
  src/main/java/database/Entity/Playlist.java
  src/main/java/database/PlaylistModel.java
Labels: bug, enhancement

#42 Djmode
  src/main/java/Main.java
  src/main/java/command/DjModeCommand.java
  src/main/java/command/GuildPlaylistCommand/AddTrackToPlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/CreatePlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/DeletePlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/DeleteTrackFromPlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/PlayPlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/RenamePlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/ShowPlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/ShowPlaylistTrackCommand.java
  src/main/java/command/JoinCommand.java
  src/main/java/command/LeaveCommand.java
  src/main/java/command/NowPlayCommand.java
  src/main/java/command/PauseCommand.java
  src/main/java/command/PlayCommand.java
  src/main/java/command/PlayUrlCommand.java
  src/main/java/command/PremiumGuildCommand.java
  src/main/java/command/PremiumUserCommand.java
  src/main/java/command/RecommendationCommand.java
  src/main/java/command/RepeatCommand.java
  src/main/java/command/ResumeCommand.java
  src/main/java/command/ShowQueueCommand.java
  src/main/java/command/ShuffleCommand.java
  src/main/java/command/SkipCommand.java
  src/main/java/command/UserPlaylistCommand/AddTrackToPlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/CreatePlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/DeletePlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/DeleteTrackFromPlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/PlayPlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/RenamePlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/ShowPlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/ShowPlaylistTrackCommand.java
  src/main/java/command/VolumeCommand.java
  src/main/java/command/YoutubeSearchCommand.java
  src/main/java/command/general/HelpCommand.java
  src/main/java/command/history/GuildHistoryCommand.java
  src/main/java/command/history/UserHistoryCommand.java
  src/main/java/database/Entity/GuildSetting.java
  src/main/java/database/UserHistoryModel.java
  src/main/java/service/music/GuildMusicManager.java
  src/main/java/service/music/HelpProcess.java
  src/main/java/service/music/MusicUtils.java
Labels: enhancement

#43 Lyric
  build.gradle
  src/main/java/Main.java
  src/main/java/command/LyricCommand.java
Labels: enhancement

#54 (Major changes) Help command detail & Guild Settings & other minor fix
  src/main/java/command/CustomAbstractCommand.java
  src/main/java/command/LyricCommand.java
  src/main/java/command/RecommendationCommand.java
  src/main/java/command/ShowGuildStateCommand.java
  src/main/java/command/ShowPaginatedQueueCommand.java
  src/main/java/command/YoutubeSearchCommand.java
  src/main/java/command/general/HelpCommand.java
  src/main/java/service/music/HelpProcess.java
Labels: enhancement

#58 Minorfix BaseModel.java
  src/main/java/database/BaseModel.java
Labels: bug

#60 Reduce user history description length
  src/main/java/database/UserHistoryModel.java
Labels: bug

#59 Custom Prefix
  py/vote_webhook.py
  src/main/java/Main.java
  src/main/java/client/CustomGuildSettingsManager.java
  src/main/java/client/NanoClient.java
  src/main/java/command/GuildPlaylistCommand/AddTrackToPlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/CreatePlaylistCommand.java
  src/main/java/command/GuildPlaylistCommand/PlayPlaylistCommand.java
  src/main/java/command/JoinCommand.java
  src/main/java/command/PlayUrlCommand.java
  src/main/java/command/RecommendationCommand.java
  src/main/java/command/ShowPaginatedQueueCommand.java
  src/main/java/command/UserPlaylistCommand/AddTrackToPlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/CreatePlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/DeletePlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/DeleteTrackFromPlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/PlayPlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/RenamePlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/ShowPlaylistCommand.java
  src/main/java/command/UserPlaylistCommand/ShowPlaylistTrackCommand.java
  src/main/java/command/YoutubeSearchCommand.java
  src/main/java/command/general/CustomPrefixCommand.java
  src/main/java/command/general/HelpCommand.java
  src/main/java/command/general/InviteCommand.java
  src/main/java/command/general/VoteCommand.java
  src/main/java/database/BaseModel.java
  src/main/java/database/Entity/GuildSetting.java
  src/main/java/database/GuildModel.java
  src/main/java/service/music/AudioLoadResultHandlerKeyword.java
  src/main/java/service/music/AudioLoadResultHandlerUrl.java
  src/main/java/service/music/GuildMusicManager.java
  src/main/java/service/music/MusicService.java
Labels: enhancement

#63 Improve performance & Simplify codes
  src/main/java/command/general/HelpCommand.java
  src/main/java/command/music/SaveQueueToPlaylistCommand.java
  src/main/java/command/playlist/guild/AddTrackToPlaylistCommand.java
  src/main/java/command/playlist/user/AddTrackToPlaylistCommand.java
  src/main/java/command/playlist/user/DeletePlaylistCommand.java
  src/main/java/command/playlist/user/DeleteTrackFromPlaylistCommand.java
  src/main/java/command/playlist/user/PlayPlaylistCommand.java
  src/main/java/command/playlist/user/ShowPlaylistTrackCommand.java
  src/main/java/database/PlaylistModel.java
  src/main/java/database/UserPlaylistModel.java
Labels: enhancement, invalid

#68 Fix youtube
  build.gradle
  src/main/java/command/music/YoutubeSearchCommand.java
Labels: enhancement

#69 Development: Deafened by default
  build.gradle
  py/vote_webhook.py
  src/main/java/command/music/JoinCommand.java
  src/main/java/command/music/KaraokeModeCommand.java
  src/main/java/command/owner/ApplyBassFilterCommand.java
  src/main/java/listener/MemberVoiceListener.java
  src/main/java/service/music/filter/BassBoostFilter.java
  src/main/java/service/music/filter/CustomFilter.java
  src/main/java/service/music/setting/BoostSetting.java
Labels: enhancement

#72 Development: Update LyricCommand and Minor fixes
  build.gradle
  scripts/global_reset.py
  scripts/global_reset.sh
  scripts/run_bot.sh
  scripts/run_mysql_server.sh
  scripts/vote_webhook.py
  src/main/java/client/NanoClient.java
  src/main/java/command/music/JoinCommand.java
  src/main/java/command/music/LeaveCommand.java
  src/main/java/command/music/LyricCommand.java
  src/main/java/listener/MemberVoiceListener.java
  src/main/java/service/music/MusicService.java
Labels: enhancement

#73 Update YoutubeIpRotatorSetup
  src/main/java/client/NanoClient.java
Labels: bug
